name: Advertising in NYC
favicon: null
layout_spectrum: 0.70226
typography_spectrum: 0.92864
title: 'Advertising in NYC Creative, Design , Print, Website and Publishing. 718.749.3520'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1875
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
