name: Advertising in NYC
favicon: null
layout_spectrum: 0.5296773174777627
typography_spectrum: 0.87794
title: 'Advertising in NYC Creative, Design , Print, Website and Publishing.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9375
  lightness: 0.7711357418447733
  saturation: 0.058211554773151875
  rhythmicContrast: 0.649190419819206
purpose: []
